import React from "react"; // Import React library for building the component
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter"; // Import the AppRouterCacheProvider component from Material UI, which is used to wrap the application and provide caching for client-side routing in Next.js applications. This helps improve performance by caching route data and reducing the need for repeated data fetching when navigating between pages.
import type { Metadata } from "next"; // Import the Metadata type from Next.js for defining metadata for the application
//import { Roboto } from "next/font/google";
import "./globals.css";
import Providers from "@/layout/providers"; // Import the Providers component from the layout directory, which is used to wrap the application with necessary context providers for state management, theming, or other global configurations.
/*
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});
*/
// This is the RootLayout component, which serves as the main layout for the application. It wraps the entire application with necessary providers and sets up the HTML structure for the pages. The component also defines metadata for the application, such as the title and description, which can be used for SEO and browser tab display. The layout includes a cache provider for client-side routing and a custom Providers component to manage global state and configurations.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-US" suppressHydrationWarning>
      {/*<html lang="en-US" className={roboto.variable} suppressHydrationWarning>*/}
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <Providers>{children}</Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
